version: "3.8"
services:
  api:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ODS_PATH=/app/src/data/final_maliyet_sistemi.ods
